### ISSUE TITLE
PT-BR Lang is present in non-beta, but broken

### ISSUE THREAD

**Issue by NCSGeek** [ProjectCeleste/Celeste.Launcher#79]
In version 2.2.1.0 there is no case in the switch statement for pt-br so it defaults to the exception, seen here:
[https://hastebin.com/axoxoquhis.cs](https://hastebin.com/axoxoquhis.cs)

Yet in the language choosing form, it has an option for PT-BR. Seen here:
[https://hastebin.com/gajopataju.cs](https://hastebin.com/gajopataju.cs)

Because of this, the switch statement defaults to throwing the exception when PT-BR is chosen.

**Comment by martinmine** [comment]
Version 2.x of the launcher will no longer be maintained as it is superseded by 3.x. I will go ahead and close this issue.
