### ISSUE TITLE
Cannot update.

### ISSUE THREAD

**Issue by jc0rtes** [ProjectCeleste/Celeste.Launcher#94]
# Describe the question
Here is my log

[launcherlog20201127.log](https://github.com/ProjectCeleste/Celeste.Launcher/files/5605880/launcherlog20201127.log)

**Comment by martinmine** [comment]
If you are going to take the effort to submit an issue, you might as well give some more context ;) For example, I don't know if you are trying to update the launcher or the game files.

The log says
```
System.UnauthorizedAccessException: Acceso denegado a la ruta de acceso 'C:\Program Files (x86)\Steam\steamapps\common\Age Of Empires Online\CelesteConfig.xml.bak'.
```
So my guess is that either this file is missing or the launcher doesnt have access to it.

**Comment by martinmine** [comment]
Closing this due to lack of information and no new information has been given within the past 9 days.
