### ISSUE TITLE
Email address containing a plus sign is reported as invalid

### ISSUE THREAD

**Issue by steffendietz** [ProjectCeleste/Celeste.Launcher#97]
# Describe the bug

When registering through the CelesteLauncher with an email address containing a plus sign (`+`) in the local-part of the address, for example `username+aoeoceleste@gmail.com`, it is falsely reported as invalid.

For reference:
* https://www.cs.rutgers.edu/~watrous/plus-signs-in-email-addresses.html
* https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/plus-addressing-in-exchange-online
* https://gmail.googleblog.com/2008/03/2-hidden-ways-to-get-more-from-your.html

## Steps to reproduce

1. Open the CelesteLauncher
2. Click "Register"
3. Type `username+aoeoceleste@gmail.com` into the "Email" field
4. Click "Verify"

## Expected behavior

I expected to get an email containing my verification key

**Comment by martinmine** [comment]
Hey, sorry for completely missing this. I have written a patch for this in 912d103 to allow + in email addresses. To make this fully take effect I have to adjust a server-side validation as well which will be deployed some time next month when we do a server patch.

**Comment by steffendietz** [comment]
Hi. Thank you. That's very much appreciated. 👍
